# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Adafruit-Blinka" = super.buildPythonPackage rec {
    pname = "Adafruit-Blinka";
    version = "8.39.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/04/0a7953a2ca7e6907341377b289f1237bae76b70b646b862b8d1ce0c04030/Adafruit_Blinka-8.39.0-py3-none-any.whl";
      sha256 = "055kchnxclnqzjn4i841jmna5mg09nlsnnz600jwpa8l8ws1ir7v";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Adafruit-PlatformDetect"
      self."Adafruit-PureIO"
      # self."adafruit-circuitpython-typing"
      self."pyftdi"
    ];
  };
  "Adafruit-PlatformDetect" = super.buildPythonPackage rec {
    pname = "Adafruit-PlatformDetect";
    version = "3.72.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9f/80/f6ed00cfb6511fd7514c51d781d83eb668c7f9a2996201002eb4ee388617/Adafruit_PlatformDetect-3.72.1-py3-none-any.whl";
      sha256 = "1mbg4abzchayjxvwkcw542qf390mi21ckvnlwgvsiad4ai8am835";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "Adafruit-PureIO" = super.buildPythonPackage rec {
    pname = "Adafruit-PureIO";
    version = "1.1.11";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/9d/28e9d12f36e13c5f2acba3098187b0e931290ecd1d8df924391b5ad2db19/Adafruit_PureIO-1.1.11-py3-none-any.whl";
      sha256 = "0kijkl1gmvji9mvc8kk9xn71pwnbjs4r29k3qbn0vk3jjc4v46i8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "adafruit-circuitpython-busdevice" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-busdevice";
    version = "5.2.9";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/0d/6d730f9b0867437d701503792988abe663a09c7a3a5fcd98c19ce3c94681/adafruit_circuitpython_busdevice-5.2.9-py3-none-any.whl";
      sha256 = "07y5pb5q4132vrkfh8ppn2gmr9h81fnavw9r6x7mlydk3ramq93q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      # self."Adafruit-Blinka"
      # self."adafruit-circuitpython-typing"
    ];
  };
  "adafruit-circuitpython-connectionmanager" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-connectionmanager";
    version = "3.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/99/1029d4a266530fe8bdabc7129ae2f91ca3dd25899cc21f6fa229413b0f7a/adafruit_circuitpython_connectionmanager-3.1.1-py3-none-any.whl";
      sha256 = "0h4m2b01lfrzq2dcv89q6xj4gcfqb3gdrxq7l1cqn815ikqz0v8b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Adafruit-Blinka"
    ];
  };
  "adafruit-circuitpython-framebuf" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-framebuf";
    version = "1.6.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e0/9f/4e98768789c3ea9e8641fb279542ae3b52c0f5a2b6955357b7afaa50308d/adafruit_circuitpython_framebuf-1.6.5-py3-none-any.whl";
      sha256 = "1hjj3f49a0x8zaf60py32hhvpma81fga5jgwwd42mhrij043fhbj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Adafruit-Blinka"
    ];
  };
  "adafruit-circuitpython-requests" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-requests";
    version = "4.1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/98/78/765c6fa3e360e322b16c0cefb37ed7a68ee9227732610d0a81b539fb70b9/adafruit_circuitpython_requests-4.1.4-py3-none-any.whl";
      sha256 = "1gj7iss0qj64q512r77x4as0yhs7g7gzqybh5ah7npxwvpsii7ai";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Adafruit-Blinka"
      self."adafruit-circuitpython-connectionmanager"
    ];
  };
  "adafruit-circuitpython-ssd1306" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-ssd1306";
    version = "2.12.17";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f1/9e/e5ce66568a2b394286b636dfe08c43f1ed8abbe461383976f54f6afe64d6/adafruit_circuitpython_ssd1306-2.12.17-py3-none-any.whl";
      sha256 = "01n1wmv8l1qkijfhgc5nwz0hgj4afijzg2n3pr555xypz7ssy8pn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."Adafruit-Blinka"
      self."adafruit-circuitpython-busdevice"
      self."adafruit-circuitpython-framebuf"
    ];
  };
  "adafruit-circuitpython-typing" = super.buildPythonPackage rec {
    pname = "adafruit-circuitpython-typing";
    version = "1.10.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/a2/e3dff5327a527468c50d814a335370ddbcc8e90898560ea0a2e9b1c8ce95/adafruit_circuitpython_typing-1.10.3-py3-none-any.whl";
      sha256 = "060cjx2qsxwxpbn7m72bap6f5y4gdgqd7msgapylvypain1dc8sf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      # self."Adafruit-Blinka"
      # self."adafruit-circuitpython-busdevice"
      self."adafruit-circuitpython-requests"
      self."typing-extensions"
    ];
  };
  "pyftdi" = super.buildPythonPackage rec {
    pname = "pyftdi";
    version = "0.55.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/03/ef/1d6dd88ec0a3e6741f0b1f7561b30d6715ecbf3bae7b2777e74439f3fff3/pyftdi-0.55.4-py3-none-any.whl";
      sha256 = "119c0wy821nvrhklj2mdij2112d1pdyqdxvxi4snjbk53km09a34";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pyserial"
      self."pyusb"
    ];
  };
  "pyserial" = super.buildPythonPackage rec {
    pname = "pyserial";
    version = "3.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/07/bc/587a445451b253b285629263eb51c2d8e9bcea4fc97826266d186f96f558/pyserial-3.5-py2.py3-none-any.whl";
      sha256 = "1w1c5z0gxvjcl73n828pvrfwb9b7mrxyrcwz575ac71rpav1sif4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyusb" = super.buildPythonPackage rec {
    pname = "pyusb";
    version = "1.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/15/a8/4982498b2ab44d1fcd5c49f07ea3795eab01601dc143b009d333fcace3b9/pyusb-1.2.1-py3-none-any.whl";
      sha256 = "0dpa94j1gsrzg8br59vqpqyh25yjkzv4yflxzd6h9pxsdnw7qk1b";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.12.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/26/9f/ad63fc0248c5379346306f8668cda6e2e2e9c95e01216d2b8ffd9ff037d0/typing_extensions-4.12.2-py3-none-any.whl";
      sha256 = "03bhjivpvdhn4c3x0963z89hv7b5vxr415akd1fgiwz0a41wmr84";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
